name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #python version of the project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file

      - name: Run tests
        run: python test.py

  deploy:  # This job will only run if the 'test' job succeeds
    needs: test
    if: success()  # Only run if the previous job succeeds
    runs-on: ubuntu-latest
    # Optional: Define an environment name
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials (refer to step 3)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "AWS credentials configured"  # Placeholder, replace with actual configuration

      - name: Deploy to AWS Elastic Beanstalk (refer to step 3)
        # Add specific deployment commands using the AWS CLI or SDK here
        run: echo "Deploying to AWS Elastic Beanstalk..."  # Placeholder, replace with actual deployment commands

